(function(){
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const api=()=>window.NIACApi, core=()=>window.NIACCore; const retrying=new Set(); let clockTimer,currentState,clockOffset=0;
  function message(el,text,error=false){if(!el)return;el.textContent=text||'';el.classList.toggle('error',error)}
  function escape(value){const span=document.createElement('span');span.textContent=value??'';return span.innerHTML}
  function connection(ok){const el=$('#connection-status');if(el){el.classList.toggle('online',ok);$('.status-text',el).textContent=ok?'Live':'Reconnecting'}}
  async function initWelcomeMap(){const svg=$('#welcome-map'),geo=window.NIGERIA_GEOJSON;if(!svg||!geo)return;const box=geo.bbox||[2.67,4.27,14.67,13.89],sx=x=>24+(x-box[0])/(box[2]-box[0])*272,sy=y=>306-(y-box[1])/(box[3]-box[1])*282;const polygons=geo.geometry.type==='MultiPolygon'?geo.geometry.coordinates:[geo.geometry.coordinates];const d=polygons.flatMap(poly=>poly.map(ring=>ring.map((p,i)=>`${i?'L':'M'}${sx(p[0]).toFixed(1)},${sy(p[1]).toFixed(1)}`).join('')+'Z')).join('');$('#welcome-map-shape').setAttribute('d',d);$('#welcome-map-clip-path').setAttribute('d',d);const positions=[[160,75,22],[104,118,17],[205,142,16],[145,180,20],[210,218,14],[112,244,16],[164,278,14]],fallback=['Roots','Realities','Renewals','Naija','Unity','Joy','Home'];async function refresh(){let words=fallback,count=0;try{const data=await api().request('/lens/approved');count=data.responses.length;if(count)words=data.responses.slice(-7).reverse().map(x=>x.phrase)}catch{}const layer=$('#welcome-map-words');layer.innerHTML='';words.forEach((word,i)=>{const [x,y,size]=positions[i%positions.length],text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',x);text.setAttribute('y',y);text.setAttribute('font-size',Math.max(11,size-Math.max(0,word.length-10)*.65));text.setAttribute('text-anchor','middle');text.setAttribute('transform',`rotate(${i%2?'-4':'3'} ${x} ${y})`);text.textContent=word;layer.appendChild(text)});$('#welcome-map-count').textContent=count?`${count} live ${count===1?'response':'responses'}`:'Waiting for your words'}await refresh();setInterval(refresh,12000)}
  async function initWelcome(){const form=$('#join-form'),recovery=$('#recovery-form');form?.addEventListener('submit',async e=>{e.preventDefault();const result=core().validateAlias($('#alias').value),msg=$('#join-message');if(!result.valid)return message(msg,result.error,true);try{$('#join-button').disabled=true;const data=await api().join(result.value);$('#join-panel').classList.add('hidden');$('#joined-panel').classList.remove('hidden');$('#recovery-code').textContent=data.recoveryCode;$('#continue-link').href=new URLSearchParams(location.search).get('next')||'/activities'}catch(err){message(msg,err.message,true)}finally{$('#join-button').disabled=false}});recovery?.addEventListener('submit',async e=>{e.preventDefault();try{await api().recover($('#recovery-code-input').value);location.href='/activities'}catch(err){message($('#recovery-message'),err.message,true)}});if(api().getProfile()){$('#existing').classList.remove('hidden');$('#existing-name').textContent=api().getProfile().alias}initWelcomeMap()}
  function guard(){return api().requireParticipant()}
  function renderParticipantLive(s){
    const card=$('#participant-live-card');if(!card)return;
    const badge=$('#participant-live-badge'),badgeText=$('#participant-live-badge-text'),activity=$('#participant-live-activity'),question=$('#participant-live-question'),status=$('#participant-live-status'),link=$('#participant-live-link');
    if(s.activity==='lens'){
      card.classList.remove('hidden');badge.classList.add('is-live');badgeText.textContent='Live now';activity.textContent='Nigeria Through Your Lens';question.textContent='Add your word to the live Nigeria map';status.textContent='Your approved response will appear on the shared screen.';link.href='/lens';link.textContent='Share your lens';return
    }
    const visible=s.question&&['open','locked','revealed','leaderboard'].includes(s.state);
    if(!visible){card.classList.add('hidden');return}
    const isOpen=s.state==='open';card.classList.remove('hidden');badge.classList.toggle('is-live',isOpen);badgeText.textContent=isOpen?'Live now':'On the main screen';activity.textContent=s.question.title||(s.activity==='decode'?'Decode the State':'Naija Passport Challenge');question.textContent=s.question.clue||s.question.question;status.textContent=isOpen?'Answers are open — tap below to choose yours.':s.state==='locked'?'Answers are closed. You can still view the question.':s.state==='revealed'?'The answer has been revealed on the main screen.':'The leaderboard is on the main screen.';link.href='/play';link.textContent=isOpen?'Answer now':'View question'
  }
  async function loadParticipantLive(){try{renderParticipantLive(await api().request('/state'))}catch{const card=$('#participant-live-card');if(card)card.classList.add('hidden')}}
  function initActivities(){if(!guard())return;$('#participant-name').textContent=api().getProfile()?.alias||'Guest';loadParticipantLive();setInterval(loadParticipantLive,2500)}
  function initLens(){if(!guard())return;const input=$('#lens-phrase'),counter=$('#lens-counter');input.addEventListener('input',()=>counter.textContent=`${input.value.length}/72`);$('#lens-form').addEventListener('submit',async e=>{e.preventDefault();const valid=core().validateLensPhrase(input.value,72);if(!valid.valid)return message($('#lens-message'),valid.error,true);try{$('#lens-submit').disabled=true;const data=await api().request('/lens',{method:'POST',body:{phrase:valid.value}});$('#lens-form').classList.add('hidden');$('#lens-success').classList.remove('hidden');$('#lens-result').textContent=`“${data.submission.phrase}”`}catch(err){message($('#lens-message'),err.message,true)}finally{$('#lens-submit').disabled=false}})}
  async function loadState(){try{const data=await api().request('/state');clockOffset=new Date(data.serverNow)-Date.now();currentState=data;connection(true);renderPlay(data);if(data.state==='leaderboard')renderLeaderboard(data.question?.activity||'passport');else renderDisplay(data);return data}catch{const fallback={state:'lobby',question:null,responseCount:0,serverNow:new Date().toISOString()};currentState=fallback;connection(false);renderPlay(fallback);renderDisplay(fallback);return fallback}}
  function remaining(s){return Math.max(0,Math.ceil((new Date(s.deadlineAt).getTime()-(Date.now()+clockOffset))/1000))}
  function renderPlay(s){const root=$('#play-root');if(!root)return;const prior=s.question&&JSON.parse(localStorage.getItem(`niac-answer-${s.question.id}`)||'null');if(!s.question||!['open','locked','revealed','leaderboard'].includes(s.state)){root.innerHTML=`<div class="panel"><p class="eyebrow">${escape(s.question?.title||'Naija Passport Challenge')}</p><h1>${s.state==='paused'?'The host has paused the activity':'Waiting for the next question'}</h1><p class="muted">Keep this screen open. It will update when the host is ready.</p></div>`;return}const q=s.question,revealed=['revealed','leaderboard'].includes(s.state);root.innerHTML=`<div class="panel"><div class="question-meta"><span>${escape(q.category)} · ${q.activity==='decode'?`Clue ${q.clueNumber}`:'Question'}</span><strong class="timer" id="timer">${remaining(s)}</strong></div><h1>${escape(q.clue||q.question)}</h1>${q.imageUrl?`<img src="${escape(q.imageUrl)}" alt="${escape(q.altText||'')}" class="question-image">`:''}<div class="answers">${q.options.map((o,i)=>`<button class="answer ${prior?.optionIndex===i?'selected':''} ${prior?.confirmed?'confirmed':''} ${revealed&&q.correctOption===i?'correct':''}" data-option="${i}" ${s.state!=='open'||prior?'disabled':''}>${String.fromCharCode(65+i)}. ${escape(o)}</button>`).join('')}</div><p id="answer-message" class="muted">${prior?.confirmed?'Answer confirmed by the server.':prior&&s.state==='open'?'Retrying your selected answer…':s.state==='open'?'Choose one answer. Once confirmed, it cannot be changed.':'Answers are locked.'}</p>${revealed?`<div class="notice"><strong>${prior&&q.correctOption===prior.optionIndex?'Correct':'Answer revealed'}</strong><br>${escape(q.explanation||'')}</div>`:''}<p id="personal-live-score" class="muted"></p></div>`;$$('.answer',root).forEach(b=>b.addEventListener('click',()=>submitAnswer(Number(b.dataset.option),s)));startClock(s);updateLiveScore(q.activity);if(prior&&!prior.confirmed&&s.state==='open')retryPending(prior,s)}
  async function updateLiveScore(activity){try{const d=await api().request('/me'),el=$('#personal-live-score');if(el){if(el.parentElement?.querySelector('.notice'))el.parentElement.querySelector('h1')?.after(el);el.textContent=activity==='decode'?`Your Decode score: ${d.scores.decode} points`:`Your total: ${d.scores.combined.toLocaleString()} points · Current rank: #${d.rank}`}}catch{}}
  function startClock(s){clearInterval(clockTimer);const tick=()=>{const el=$('#timer');if(el)el.textContent=remaining(s)};tick();clockTimer=setInterval(tick,250)}
  async function submitAnswer(optionIndex,s){$$('.answer').forEach((b,i)=>b.classList.toggle('selected',i===optionIndex));message($('#answer-message'),'Sending…');const key=`niac-answer-${s.question.id}`,pending={optionIndex,idempotencyKey:crypto.randomUUID(),confirmed:false};localStorage.setItem(key,JSON.stringify(pending));try{await api().request('/answers',{method:'POST',body:{sessionId:s.sessionId,questionId:s.question.id,optionIndex,idempotencyKey:pending.idempotencyKey}});pending.confirmed=true;localStorage.setItem(key,JSON.stringify(pending));$$('.answer').forEach(b=>b.disabled=true);message($('#answer-message'),'Answer confirmed by the server.')}catch(err){message($('#answer-message'),err.message,true);if(err.code==='ANSWER_LATE'||err.code==='QUESTION_NOT_OPEN')localStorage.removeItem(key)}}
  async function retryPending(pending,s){const key=`niac-answer-${s.question.id}`;if(retrying.has(key)||remaining(s)<=0)return;retrying.add(key);try{await api().request('/answers',{method:'POST',body:{sessionId:s.sessionId,questionId:s.question.id,optionIndex:pending.optionIndex,idempotencyKey:pending.idempotencyKey}});pending.confirmed=true;localStorage.setItem(key,JSON.stringify(pending));message($('#answer-message'),'Answer confirmed by the server.')}catch(err){if(err.code==='ANSWER_LATE'||err.code==='QUESTION_NOT_OPEN')localStorage.removeItem(key);message($('#answer-message'),err.message,true)}finally{retrying.delete(key)}}
  function initPlay(){if(!guard())return;loadState();setInterval(loadState,2500)}
  async function initPassport(){if(!guard())return;try{const d=await api().request('/me');$('#passport-name').textContent=d.participant.alias;['day1','day2','combined','decode'].forEach(k=>$('#score-'+k).textContent=d.scores[k]);$('#score-rank').textContent=`#${d.rank}`;const earned=new Set(d.stamps.map(x=>x.category));$$('.stamp').forEach(x=>x.classList.toggle('earned',earned.has(x.dataset.category)))}catch(err){message($('#passport-message'),err.message,true)}}
  function renderDisplay(s){const root=$('#display-root');if(!root)return;if(s.activity==='lens'){if(!$('#lens-projector-frame',root))root.innerHTML='<iframe id="lens-projector-frame" class="lens-projector-frame" src="/lens/live?embed=1" title="Nigeria Through Your Lens live mosaic"></iframe>';return}if(!s.question){const joinUrl=location.origin+'/';const qr=`https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=12&data=${encodeURIComponent(joinUrl)}`;root.innerHTML=`<section class="display-welcome"><div><p>Shell Companies in Nigeria</p><h1>NIAC Live</h1><h2>Timeless Nigeria:<br>Roots, Realities & Renewals</h2></div><div class="join-box"><div class="qr-placeholder"><span>Join at<br>${escape(location.host)}</span><img src="${qr}" alt="QR code to join NIAC Live"></div><strong>Scan to join</strong><span>${escape(location.host)}</span></div></section>`;$('.qr-placeholder img')?.addEventListener('error',e=>e.currentTarget.remove());return}const q=s.question,reveal=['revealed','leaderboard'].includes(s.state);root.innerHTML=`<section class="display-question"><header><span>${escape(q.title)}</span><strong>${escape(q.activity==='decode'?`Clue ${q.clueNumber}`:q.category)}</strong></header><div class="display-timer">${remaining(s)}</div><h1>${escape(q.clue||q.question)}</h1><div class="display-options">${q.options.map((o,i)=>`<div class="${reveal&&q.correctOption===i?'correct':''}">${String.fromCharCode(65+i)}. ${escape(o)}</div>`).join('')}</div><footer><span>${s.responseCount} answers received</span><span>${escape(s.state)}</span></footer>${reveal?`<aside>${escape(q.explanation||'')}${q.highlightState?` · Highlight: ${escape(q.highlightState)} State`:''}</aside>`:''}</section>`}
  async function renderLeaderboard(activity){const root=$('#display-root');if(!root)return;try{const d=await api().request(`/leaderboard?activity=${activity}`);root.innerHTML=`<section class="display-question"><header><span>${activity==='decode'?'Decode the State':'Naija Passport Challenge'}</span><strong>Top ten</strong></header><h1>Leaderboard</h1><ol class="leaderboard">${d.leaders.map((x,i)=>`<li><span>${i+1}. ${escape(x.alias)}</span><strong>${x.totalScore.toLocaleString()}</strong></li>`).join('')}</ol><footer><span>NIAC Live</span><span>${activity==='decode'?'Separate game score':'Cumulative Day 1 + Day 2'}</span></footer></section>`}catch{renderDisplay(currentState)}}
  function initDisplay(){loadState();setInterval(loadState,2000);setInterval(()=>currentState&&renderDisplay(currentState),500)}
  async function adminLogin(){const email=$('#admin-email').value,password=$('#admin-password').value;try{const {data,error}=await supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY).auth.signInWithPassword({email,password});if(error)throw error;api().setAdminToken(data.session.access_token);location.reload()}catch(err){message($('#admin-login-message'),err.message,true)}}
  async function initAdmin(){
    if(!api().hasAdmin()&&['127.0.0.1','localhost'].includes(location.hostname)){try{const local=await api().request('/dev/admin',{method:'POST'});api().setAdminToken(local.token)}catch{}}
    if(!api().hasAdmin()){$('#admin-login').classList.remove('hidden');$('#admin-login-button').addEventListener('click',adminLogin);return}
    $('#control-room').classList.remove('hidden');let status;
    try{status=await api().request('/admin/status',{admin:true});$('#admin-name').textContent=status.admin.displayName;$('#live-state').textContent=status.session?.state||'Not configured';$('#admin-participants').textContent=status.metrics.participants;$('#admin-responses').textContent=status.metrics.responseCount;$('#activity-select').value=status.settings?.active_activity||'lens';$('#rehearsal-mode').checked=Boolean(status.settings?.rehearsal_mode);status.questions.forEach(q=>$('#question-select').add(new Option(`${q.category}: ${q.question}`,q.id)))}catch(err){api().clearAdmin();message($('#admin-login-message'),err.message,true);$('#admin-login').classList.remove('hidden');$('#control-room').classList.add('hidden');return}
    $$('[data-state]').forEach(b=>b.addEventListener('click',async()=>{try{await api().request('/admin/action',{method:'POST',admin:true,body:{state:b.dataset.state}});location.reload()}catch(err){message($('#admin-message'),err.message,true)}}));
    $('#select-question').addEventListener('click',async()=>{const questionId=$('#question-select').value;if(!questionId)return message($('#admin-message'),'Choose an approved question first.',true);try{await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'select_question',questionId}});location.reload()}catch(err){message($('#admin-message'),err.message,true)}});
    $('#next-clue').addEventListener('click',async()=>{try{await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'next_clue'}});location.reload()}catch(err){message($('#admin-message'),err.message,true)}});
    $('#save-settings').addEventListener('click',async()=>{try{await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'set_settings',activeActivity:$('#activity-select').value,rehearsalMode:$('#rehearsal-mode').checked}});message($('#admin-message'),'Event settings saved.')}catch(err){message($('#admin-message'),err.message,true)}});
    $('#clear-rehearsal').addEventListener('click',()=>clearData('rehearsal','CLEAR REHEARSAL DATA'));
    $('#reset-production').addEventListener('click',()=>clearData('production','RESET NIAC 2026 PRODUCTION DATA'));
    $('#void-question').addEventListener('click',async()=>{if(!confirm('Void the current question and remove its points from every score?'))return;try{await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'void_question'}});location.reload()}catch(err){message($('#admin-message'),err.message,true)}});
    await loadModeration();
  }
  async function clearData(scope,required){const confirmText=prompt(`Type ${required} exactly to continue.`);if(confirmText!==required)return;try{const d=await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'clear_data',scope,confirmText}});message($('#admin-message'),`${d.cleared} participant profiles cleared.`)}catch(err){message($('#admin-message'),err.message,true)}}
  async function loadModeration(){const body=$('#moderation-body');if(!body)return;try{const d=await api().request('/admin/lens',{admin:true});body.innerHTML=d.responses.map(r=>`<tr><td>${escape(r.phrase)}</td><td>${escape(r.participants?.alias||'Legacy')}</td><td>${escape(r.status)}</td><td><button class="button secondary" data-moderate="${r.id}" data-status="approved">Restore</button> <button class="button secondary" data-edit="${r.id}" data-phrase="${escape(r.phrase)}">Edit</button> <button class="button secondary" data-moderate="${r.id}" data-status="hidden">Hide</button></td></tr>`).join('')||'<tr><td colspan="4">No responses yet.</td></tr>';$$('[data-moderate]').forEach(b=>b.addEventListener('click',async()=>{await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'moderate',id:b.dataset.moderate,status:b.dataset.status}});loadModeration()}));$$('[data-edit]').forEach(b=>b.addEventListener('click',async()=>{const phrase=prompt('Correct an obvious spelling error:',b.dataset.phrase);if(phrase==null)return;await api().request('/admin/action',{method:'POST',admin:true,body:{kind:'moderate',id:b.dataset.edit,status:'approved',phrase}});loadModeration()}));$('#export-lens').onclick=()=>{const csv=['phrase,alias,status,created_at',...d.responses.map(r=>[r.phrase,r.participants?.alias||'Legacy',r.status,r.created_at].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`niac-lens-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}}catch(err){message($('#admin-message'),err.message,true)}}
  async function initContent(){if(!api().hasAdmin()&&['127.0.0.1','localhost'].includes(location.hostname)){try{const local=await api().request('/dev/admin',{method:'POST'});api().setAdminToken(local.token)}catch{}}if(!api().hasAdmin()){location.href='/admin';return}try{const d=await api().request('/admin/content',{admin:true});$('#content-body').innerHTML=d.questions.map(q=>`<tr><td>${escape(q.category)}</td><td>${escape(q.question)}</td><td>${escape(q.review_status)}</td><td>${q.duration_seconds}s</td></tr>`).join('')||'<tr><td colspan="4">Import the supplied question bank.</td></tr>'}catch(err){message($('#content-message'),err.message,true)}}
  const initializers={welcome:initWelcome,activities:initActivities,lens:initLens,play:initPlay,passport:initPassport,display:initDisplay,admin:initAdmin,content:initContent};document.addEventListener('DOMContentLoaded',()=>initializers[document.body.dataset.page]?.());
})();
