import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const routes={"/":"index.html","/activities":"activities.html","/lens":"lens.html","/lens/live":"lens-live.html","/play":"play.html","/passport":"passport.html","/display":"display.html","/admin":"admin.html","/admin/content":"admin-content.html"};
for(const [route,file] of Object.entries(routes))test(`route ${route} has an application document`,async()=>{const html=await readFile(new URL(`../${file}`,import.meta.url),'utf8');assert.match(html,/<html/i)});
test('participant, display and admin flows have required entry points',async()=>{const [join,play,display,admin]=await Promise.all(['index.html','play.html','display.html','admin.html'].map(f=>readFile(new URL(`../${f}`,import.meta.url),'utf8')));assert.match(join,/join-form/);assert.match(play,/play-root/);assert.match(display,/display-root/);assert.match(admin,/admin-login/)});
test('participant hub mirrors the active question',async()=>{const [activities,script]=await Promise.all(['activities.html','js/app.js'].map(f=>readFile(new URL(`../${f}`,import.meta.url),'utf8')));assert.match(activities,/participant-live-question/);assert.match(activities,/aria-live="polite"/);assert.match(script,/renderParticipantLive/);assert.match(script,/setInterval\(loadParticipantLive,2500\)/)});
test('admin includes a one-click cue desk and editable question bank',async()=>{const [admin,content,script]=await Promise.all(['admin.html','admin-content.html','js/admin-console.js'].map(f=>readFile(new URL(`../${f}`,import.meta.url),'utf8')));assert.match(admin,/Open question/);assert.match(admin,/Show Top 10/);assert.match(admin,/Pause everything/);assert.doesNotMatch(admin,/Prepare question/);assert.match(content,/question-editor/);assert.match(content,/correct-option/);assert.match(script,/open_question/);assert.match(script,/Save question|saveQuestion/)});
test('question timers reveal answers automatically in local and deployed APIs',async()=>{const [local,remote]=await Promise.all(['scripts/dev-server.mjs','netlify/functions/api.mjs'].map(f=>readFile(new URL(`../${f}`,import.meta.url),'utf8')));for(const source of [local,remote]){assert.match(source,/autoReveal/);assert.match(source,/revealed/);assert.match(source,/open_question/)}});
