// Photo licences checked against Wikimedia imageinfo on 2026-09-17.
const commons = title => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(title.replaceAll(' ', '_'))}`;
export const assets = {
  hibiscus: {src:'/review/assets/10.jpg', title:'Hibiscus Sabdariffa calyxes', author:'Earl Benton', license:'CC BY-SA 4.0', licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:commons('Hibiscus Sabdariffa calyxes.jpg'), alt:'A fresh, deep-red hibiscus calyx on the plant.', caption:'The fleshy calyces are harvested and dried to make zobo. This photograph shows a fresh calyx.', timing:'reveal'},
  suya: {src:'/review/assets/09.jpg', title:'Suya in skewers', author:'Halima Waziri', license:'CC BY-SA 4.0', licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:commons('Suya in skewers.jpg'), alt:'Seasoned meat skewers arranged on a grill rack.', caption:'Suya is seasoned meat cooked over a grill.', timing:'reveal'},
  adire: {src:'/review/assets/01.jpg', title:'Aso Adire', author:'Olaniyan Olushola', license:'CC BY-SA 4.0', licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:commons('Aso Adire.jpg'), alt:'Dark fabric with pale circular and geometric patterns.', caption:'Adire uses resist-dyeing techniques to create patterns.', timing:'question'},
  puff: {src:'/review/assets/02.jpg', title:'Nigerian puff-puff', author:'Afrolems; crop by Off-shell', license:'CC BY-SA 4.0', licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:commons('Nigerian-puff-puff-recipe cropped.jpg'), alt:'Three rounded golden-brown fried snacks on a dark plate.', caption:'Puff-puff is made from a yeast-raised dough and deep-fried.', timing:'question'},
  nok: {src:'/review/assets/03.jpg', title:'Head, Nok culture, Honolulu Museum of Art, 8349.1', author:'Hiart', license:'CC0', licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/', source:commons('Head, Nok culture, terracotta, Honolulu Museum of Art, 8349.1.JPG'), alt:'A terracotta head with pierced eyes and a tall, textured hairstyle.', caption:'A Nok terracotta head in the Honolulu Museum of Art.', timing:'question'},
  danfo: {src:'/review/assets/04.jpg', title:'Fleet of Danfo buses in Lagos', author:'Kaizenify', license:'CC BY-SA 4.0', licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:commons('Fleet of Danfo buses in Lagos.jpeg'), alt:'Several small yellow minibuses on a busy Lagos street.', caption:'The small yellow minibuses are known as danfo.', timing:'question'},
};
